src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OffreRepository::class)]
class Offre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $objet = null;

    #[ORM\Column(length: 255)]
    private ?string $domaine = null;

    #[ORM\Column]
    private ?int $nombre = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\ManyToOne(inversedBy: 'offres')]
    private ?User $entreprise = null;

    #[ORM\OneToMany(mappedBy: 'offre', targetEntity: Messages::class,orphanRemoval: true, cascade: ['persist'])]
    private Collection $messages;

    #[ORM\Column(type: 'boolean')]
    private  $validated  = false;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getObjet(): ?string
    {
        return $this->objet;
    }

    public function setObjet(string $objet): static
    {
        $this->objet = $objet;

        return $this;
    }

    public function getDomaine(): ?string
    {
        return $this->domaine;
    }

    public function setDomaine(string $domaine): static
    {
        $this->domaine = $domaine;

        return $this;
    }

    public function getNombre(): ?int
    {
        return $this->nombre;
    }

    public function setNombre(int $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getEntreprise(): ?User
    {
        return $this->entreprise;
    }

    public function setEntreprise(?User $entreprise): static
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    /**
     * @return Collection<int, Messages>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Messages $message): static
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setOffre($this);
        }

        return $this;
    }

    public function removeMessage(Messages $message): static
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getOffre() === $this) {
                $message->setOffre(null);
            }
        }

        return $this;
    }

    public function isValidated(): ?bool
    {
        return $this->validated;
    }

    public function setValidated(bool $validated): static
    {
        $this->validated = $validated;

        return $this;
    }


    
    
}

src/Controller/ListeStageController.php
<?php

namespace App\Controller;

use App\Entity\Notifications;
use App\Entity\Stage;
use App\Repository\MessagesRepository;
use App\Repository\StageRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Security\EmailVerifier;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use SymfonyCasts\Bundle\VerifyEmail\VerifyEmailHelperInterface;
use Symfony\Component\Mailer\MailerInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Mime\Address;
class ListeStageController extends AbstractController
{



 private EmailVerifier $emailVerifier;
    
    
    
    public function __construct(EmailVerifier $emailVerifier,private VerifyEmailHelperInterface $verifyEmailHelper,
    private MailerInterface $mailer,private EntityManagerInterface $entityManager
    )
    {
        $this->emailVerifier = $emailVerifier;
    }





    #[Route('/liste/stage', name: 'app_liste_stage')]
    public function index(StageRepository $stageRepository): Response
    {
        $entrepriseId= $this->getUser() ;
        $stages = $stageRepository->findByEntreprise($entrepriseId);
        
        return $this->render('liste_stage/index.html.twig', [
            'stages'=> $stages
        ]);
    }


    #[Route('/liste/stage/{id}', name: 'valider')]
    public function valider(StageRepository $stageRepository,int $id,ManagerRegistry $doctrine): Response
    {
        $stage = $stageRepository->find($id); 
        $manager = $doctrine->getManager();
        $stage->setValidated("1");
        $manager->persist($stage);
        $manager->flush();

        $message = new  Notifications();
        $user = $this->getUser();
        $manager = $doctrine->getManager();
        $message->setMessage($user->getNom(). " a validé vôtre demande de stage ");
        $message->setTitre("Message de confirmation");
        $message->setStatut("unread");
        $message->setUser($user);
        $message->setStage($stage);
        $manager->persist($message);
        $manager->flush();
        

          // generate a signed url and email it to the user
            $this->emailVerifier->sendEmailConfirmation('app_verify_email', $user,
                (new TemplatedEmail())
                    ->from(new Address('houegbelossiallodegoldfroy@gmail.com', 'Goldfroy'))
                    ->to($user->getEmail())
                    ->subject('Validation')
                    ->htmlTemplate('registration/valide.html.twig')
                    
            );



        return $this->redirectToRoute('app_liste_stage');
    }

    #[Route('/liste/{id}/reject', name: 'reject')]
   public function reject(int $id,ManagerRegistry $doctrine,StageRepository $stageRepository,Request $request)
   {
    
        $ids = $stageRepository->find($id);     
        $manager = $doctrine->getManager();
        $mot = $request->get('rejet');
        $ids->setReason($mot);
        $manager->persist($ids);
        $manager->flush();
        
        $notif = new Notifications(); 
        
        $user = $this->getUser();
        
        $manager = $doctrine->getManager();
        $notif->setMessage($user->getNom(). " a rejeté vôtre demande de stage ");
        $notif->setTitre("Message de rejet");
        $notif->setStatut("unread");
        $notif->setUser($user);
        $notif->setStage($ids);
        $manager->persist($notif);
        $manager->flush();
        return $this->redirectToRoute('app_liste_stage');
        
        
    
    }
    
}

templates/liste_stage/index.html.twig
{% extends 'template.html.twig' %}

{% block title %}Hello StageController!{% endblock %}

{% block body %}


<div class="container-fluid" >
<div class="card shadow mb-4">
    <div class="card-header py-3">
<div class="card-body table-responsive">
<div class="container" >
   <form action="" enctype="multipart/form-data" method="POST" role="form" class="php-email-form" style="width:700px" >
     <div class="row">
                                  <table class="table table-bordered table-striped table-highlight">

                                                    <thead>
                                                        <tr>
                                                          
                                                        <th>Nombre</th>
                                                        <th>Domaine</th>
                                                        <th>Objet</th>
                                                        <th>Nom</th>
                                                        <th>Prénom</th>
                                                        <th>Date de fin</th>
                                                        <th>cv</th>
                                                        <th>Action 1</th>
                                                        <th>Action 2</th>
                                                        <th>Action 3</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        {% for stage in stages %}
                                                        <tr>
                                                            
                                                        <td>{{stage.nombre}}</td>
                                                        <td> {{stage.dmaine}} </td>
                                                        <td> {{stage.objet}} </td>
                                                        <td> {{stage.etudiant.nom}} </td>
                                                        <td> {{stage.etudiant.prenom}} </td>
                                                        <td> {{stage.dateFin|date("d/m/Y")}} </td>
                                                       <td> <img src="{{asset('uploads/users/'~ stage.cv)}}" alt="" width="50%"> </td>
                                                        <td>
                                                        <a href="{{ path('stage_show', {id: stage.id}   )}}" class="btn btn-primary">Détails</a>
                                                        </td>
                                                        <td>
                                                            <form action="{{ path('reject', {id : stage.id})}}" method="POST">
                            
                                                            <div>
                                                                <input type="text" name="rejet" id="rejetmot" class="form-control" placeholder="Motif du rejet" required>
                                                                
                                                            </div>
                                                            <button type="submit" class="btn btn-danger">Rejeter</button>
                                                            </form>
                                    
                                                        </td>
                                                        <td>
                                                        <a href="{{ path('valider', {id : stage.id}   )}}  " class="text text-success" >VALIDER</a>
                                                        </td>
                                                    </tr>
                                                    {% endfor %}
                                                            
                                                        
                                                    </tbody>
                                                </table>
                                            
                                        </div>
                                    </form>



                                






{% endblock %}