src/Entity/Attestation.php
<?php

namespace App\Entity;

use App\Repository\AttestationRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AttestationRepository::class)]
class Attestation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $contrat_stage = null;

    #[ORM\Column(length: 255)]
    private ?string $carte_scolaire = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'attestations')]
    private ?User $entreprise = null;

    #[ORM\ManyToOne(inversedBy: 'attestations')]
    private ?User $etudiant = null;

    public function __construct()
    {
       
        $this->created_at = new \DateTimeImmutable();
       
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContratStage(): ?string
    {
        return $this->contrat_stage;
    }

    public function setContratStage(string $contrat_stage): static
    {
        $this->contrat_stage = $contrat_stage;

        return $this;
    }

    public function getCarteScolaire(): ?string
    {
        return $this->carte_scolaire;
    }

    public function setCarteScolaire(string $carte_scolaire): static
    {
        $this->carte_scolaire = $carte_scolaire;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getEntreprise(): ?User
    {
        return $this->entreprise;
    }

    public function setEntreprise(?User $entreprise): static
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getEtudiant(): ?User
    {
        return $this->etudiant;
    }

    public function setEtudiant(?User $etudiant): static
    {
        $this->etudiant = $etudiant;

        return $this;
    }
}

src/Form/AttestationType.php
<?php

namespace App\Form;

use App\Entity\Attestation;
use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class AttestationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $Entreprise = $options['Entreprise'];
        $builder
        ->add('contrat_stage',FileType::class, [
            'label' => "Uploader votre curriculum vitae",

            // unmapped means that this field is not associated to any entity property
            'mapped' => false,

            // make it optional so you don't have to re-upload the PDF file
            // every time you edit the Product details
            'required' => true,

            // unmapped fields can't define their validation using attributes
            // in the associated entity, so you can use the PHP constraint classes
            'constraints' => [
                new File([
                    'maxSize' => '1024k',
                    'mimeTypes' => [
                        'image/jpg',
                        'image/png',
                        'image/jpeg',
                        'image/gif',
                        'image/webp',
                    ],
                    'mimeTypesMessage' => "L'image ne correspond pas aux contraintes",
                ])
            ],
        ])
        ->add('carte_scolaire',FileType::class, [
            'label' => "Uploader votre curriculum vitae",

            // unmapped means that this field is not associated to any entity property
            'mapped' => false,

            // make it optional so you don't have to re-upload the PDF file
            // every time you edit the Product details
            'required' => true,

            // unmapped fields can't define their validation using attributes
            // in the associated entity, so you can use the PHP constraint classes
            'constraints' => [
                new File([
                    'maxSize' => '1024k',
                    'mimeTypes' => [
                        'image/jpg',
                        'image/png',
                        'image/jpeg',
                        'image/gif',
                        'image/webp',
                    ],
                    'mimeTypesMessage' => "L'image ne correspond pas aux contraintes",
                ])
            ],
        ])
            ->add('entreprise',EntityType::class,array(
                'class'=> User::class,
                'choice_label'=>'nom',
                'label'=> 'Entreprise',
                'group_by'=> 'nom',
                'query_builder'=> function(UserRepository $cr)
                use($Entreprise)
                {
                    return $cr->createQueryBuilder('U')
                    ->where('U.type = :Entreprise')
                    ->setParameter('Entreprise',$Entreprise)
                    ->orderBy('U.nom', 'ASC');
                   // ->getQuery()
                   // ->getResult();
                    
                    
                }
                
            ))
            ->add('Valider',SubmitType::class)
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Attestation::class,
            'Entreprise'=> 'Entreprise',
        ]);
    }
}

src/Controller/AttestationController.php
<?php

namespace App\Controller;

use App\Entity\Attestation;
use App\Form\AttestationType;
use App\Repository\AttestationRepository;
use App\Service\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class AttestationController extends AbstractController
{
    #[Route('/attestation', name: 'app_attestation')]
    public function index(AttestationRepository $attestationRepository): Response
    {
        $etudiantId= $this->getUser() ;
    
        $attestations = $attestationRepository->findByUser($etudiantId);
        return $this->render('attestation/index.html.twig', [
            'attestations'=> $attestations
        ]);
    }



    #[Route('/attestation/add', name: 'add_attestation')]
    public function add(ManagerRegistry $doctrine, Request $request, SluggerInterface $slugger,FileUploader $file_uploader): Response
    {
        
        $attestation = new Attestation();
        $user = $this->getUser();
        $form = $this->createForm(AttestationType::class,$attestation);
        $form->handleRequest($request);
        
        if($form->isSubmitted() && $form->isValid())
        {
            $contrat_stage = $form->get('contrat_stage')->getData();
            $carte_scolaire = $form->get('carte_scolaire')->getData();
            
            if ($contrat_stage && $carte_scolaire)
            {
                $originalFilename = pathinfo($contrat_stage->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'. $contrat_stage->guessExtension();
                $originalFilename1 = pathinfo($carte_scolaire->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename1 = $slugger->slug($originalFilename1);
                $newFilename1 = $safeFilename1.'-'.uniqid().'.'. $carte_scolaire->guessExtension();
                try {
                    $contrat_stage->move(
                        $this->getParameter('users_directory'),
                        $newFilename);
                        $carte_scolaire->move(
                            $this->getParameter('users_directory'),
                            $newFilename1);
                } catch (FileException $e) {
    
                }
                
                $attestation->setContratStage($newFilename);
                $attestation->setCarteScolaire($newFilename1);
            }
              
               
            $manager = $doctrine->getManager();
            $attestation->setEtudiant($user);
            $manager->persist($attestation);
            $manager->flush();
           
            $this->addFlash("error", "a été ajouté avec succès" );
            return $this->redirectToRoute('app_attestation');
            
        }
       
        
        else{
            
            return $this->render('attestation/new.html.twig', [
                'form' => $form->createView(),
                
            ]);
            
        }
        
    }     



    #[Route('/attestation/edit/{id}', name: 'attestation_edit')]
    public function edit(Request $request,ManagerRegistry $doctrine,$id,SluggerInterface $slugger)
    {
        
       $attestation = new Attestation();
       $attestation = $doctrine->getRepository(Attestation::class)->find($id);
       $form = $this->createForm(AttestationType::class, $attestation);
       $form->handleRequest($request);
     
       if($form->isSubmitted() && $form->isValid())
       {
          
        $contrat_stage = $form->get('contrat_stage')->getData();
        $carte_scolaire = $form->get('carte_scolaire')->getData();
        
        if ($contrat_stage && $carte_scolaire)
        {
            $originalFilename = pathinfo($contrat_stage->getClientOriginalName(), PATHINFO_FILENAME);
            $safeFilename = $slugger->slug($originalFilename);
            $newFilename = $safeFilename.'-'.uniqid().'.'. $contrat_stage->guessExtension();
            $originalFilename1 = pathinfo($carte_scolaire->getClientOriginalName(), PATHINFO_FILENAME);
            $safeFilename1 = $slugger->slug($originalFilename1);
            $newFilename1 = $safeFilename1.'-'.uniqid().'.'. $carte_scolaire->guessExtension();
            try {
                $contrat_stage->move(
                    $this->getParameter('users_directory'),
                    $newFilename);
                    $carte_scolaire->move(
                        $this->getParameter('users_directory'),
                        $newFilename1);
            } catch (FileException $e) {

            }
            
            $attestation->setContratStage($newFilename);
            $attestation->setCarteScolaire($newFilename1);
        }
           $manager = $doctrine->getManager();
           $manager->persist($attestation);
           $manager->flush();
           return $this->redirectToRoute('app_attestation');
       }
       return $this->render('attestation/edit.html.twig',array(
           'form'=>$form->createView(),
           'attestation' => $attestation->getId()
       ));
    
    }


    #[Route('/attestation/delete/{id}', name: 'attestation_delete')]
    public function delete(Request $request,ManagerRegistry $doctrine, int $id): Response
    {
        $attestation = new Attestation();
        $attestation = $doctrine->getRepository(Attestation::class)->find($id);
   
        if($attestation)
        {
            $manager = $doctrine->getManager();
            $manager->remove($attestation);
            $manager->flush();
            $this->addFlash("success","Suppression réussi");
            
            return $this->redirectToRoute('app_attestation');
           
    
            
        }else{
            $this->addFlash('error','Plat inexistant');
        }
    
          return $this->redirectToRoute('app_attestation');
    }



    #[Route('/attestation/liste', name: 'liste_attestation')]
    public function list(AttestationRepository $attestationRepository): Response
    {
        
        $entrepriseId= $this->getUser() ;
        
        $attestations = $attestationRepository->findByEntreprise($entrepriseId);
        
        return $this->render('attestation/liste.html.twig', [
            'attestations'=> $attestations
        ]);
    }


    #[Route('/attestation/show/{id}', name: 'attestation_show')]
    public function show(Request $request,AttestationRepository $attestationRepository, int $id): Response
    {
        $attestation = $attestationRepository->find($id);
        return $this->render('attestation/show.html.twig', [
            'attestation'=> $attestation
        ]);
    }


    #[Route('/attestation/liste/sow/{id}', name: 'liste_attestation_show')]
    public function listes(AttestationRepository $attestationRepository,int $id): Response
    {
        
        
        
        $attestation = $attestationRepository->find($id);
        return $this->render('attestation/show.html.twig', [
            'attestation'=> $attestation
        ]);
    }









    
}

templates/attestation/edit.html.twig
{% extends 'template.html.twig' %}

{% block title %}Stages{% endblock %}

{% block PageTitle %}Nouvelle demande{% endblock %}

{% block body %}


<div class="container-fluid" >
            <div class="card shadow mb-4">
                <div class="card-header py-3">
            <div class="card-body table-responsive">
            <div class="container" >
            <form action="" enctype="multipart/form-data" method="POST" role="form" class="php-email-form" style="width:700px" >
                    {{ form_start(form) }}
                    <div class="row">

                <div class="col-6">{{ form_row(form.contrat_stage) }}</div>
                <div class="col-6"> {{ form_row(form.carte_scolaire) }} </div>

                    </div>

                    <div class="row">

                    <div class="col-12">{{ form_row(form.entreprise) }}</div>

                    </div>



                    
                    {{ form_rest(form) }}

                    <a href="{{path('app_attestation')}}">Listes des attestation</a>
                 </form>
                </div>
            </div>
            </div>
            </div>
        
{% endblock %}

templates/attestation/index.html.twig
{% extends 'template.html.twig' %}

{% block title %}Hello StageController!{% endblock %}

{% block body %}



<div class="container-fluid" >
<div class="card shadow mb-4">
    <div class="card-header py-3">
<div class="card-body table-responsive">
<div class="container" >
   <form action="" enctype="multipart/form-data" method="POST" role="form" class="php-email-form" style="width:700px" >
     <div class="row">
                                  <table class="table table-bordered table-striped table-highlight">
                                <a href="{{ path('add_attestation') }}" class="btn btn-success mb-2">Nouvelle demande</a>
                                                    <thead>
                                                        <tr>
                                                          
                                                        <th>Entreprise</th>
                                                        <th>Contrat de Stage</th>
                                                        <th>Carte Scolaire</th>
                                                        <th>Date de création</th>
                        
                                                        <th>Action 1</th>
                                                        <th>Action 2</th>
                                                        <th>Action 3</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        {% for attestation in attestations %}
                                                        <tr>
                                                            
                                                        <td>{{attestation.entreprise.nom}}</td>
                                                        <td><img src="{{asset('uploads/users/'~ attestation.contratstage)}}" alt="" width="50%"></td>
                                                        <td><img src="{{asset('uploads/users/'~ attestation.cartescolaire)}}" alt="" width="50%"></td>
                                                        <td>{{attestation.createdat|date('d/m/Y') }}</td>
                                                       
                                                        <td>
                                                        <a href="{{path('attestation_show', {id : attestation.id})}}" class="btn btn-primary">Détails</a>
                                                        </td>
                                                        <td>
                                                        <a href="{{path('attestation_delete', {id : attestation.id})}}" class="btn btn-danger" >REMOVE</a>
                                                        </td>
                                                        <td>
                                                        <a href="{{path('attestation_edit', {id : attestation.id} )}}" class="btn btn-success" >MODIFIER</a>
                                                        </td>
                                                    </tr>
                                                    
                                                            
                                                        {% endfor %}
                                                    </tbody>
                                                </table>
                                            
                                        </div>
                                    </form>



                                






{% endblock %}

templates/attestation/liste.html.twig
{% extends 'template.html.twig' %}

{% block title %}Hello StageController!{% endblock %}

{% block body %}


<div class="container-fluid" >
<div class="card shadow mb-4">
    <div class="card-header py-3">
<div class="card-body table-responsive">
<div class="container" >
   <form action="" enctype="multipart/form-data" method="POST" role="form" class="php-email-form" style="width:700px" >
     <div class="row">
                                  <table class="table table-bordered table-striped table-highlight">
                                
                                                    <thead>
                                                        <tr>
                                                          
                                                        
                                                        <th>Nom</th>
                                                        <th>Prénom</th>
                                                        <th>Ecole</th>
                                                        <th>Contrat de stage</th>
                                                        <th>Carte Scolaire</th>
                                                        <th>Date de Création</th>
                                                        <th>Action 1</th>
                                                        
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        {% for attestation in attestations %}
                                                        <tr>
                                                            
                                                        <td>{{attestation.etudiant.nom}}</td>
                                                        <td> {{attestation.etudiant.prenom}} </td>
                                                        
                                                        <td> {{attestation.etudiant.ecole}} </td>
                                                        
                                                       <td> <img src="{{asset('uploads/users/'~ attestation.contratStage)}}" alt="" width="50%"> </td>
                                                       <td> <img src="{{asset('uploads/users/'~ attestation.carteScolaire)}}" alt="" width="50%"> </td>
                                                       <td> {{attestation.createdAt|date("d/m/Y")}} </td>
                                                        <td>
                                                        <a href="{{path('liste_attestation_show', {id : attestation.id})}}" class="btn btn-primary">Détails</a>
                                                        </td>
                                                        
                                                    </tr>
                                                    {% endfor %}
                                                            
                                                        
                                                    </tbody>
                                                </table>
                                            
                                        </div>
                                    </form>



                                






{% endblock %}

templates/attestation/new.html.twig
{% extends 'template.html.twig' %}

{% block title %}Stages{% endblock %}

{% block PageTitle %}Nouvelle demande{% endblock %}

{% block body %}


            <div class="container-fluid" >
            <div class="card shadow mb-4">
                <div class="card-header py-3">
            <div class="card-body table-responsive">
            <div class="container" >
            <form action="" enctype="multipart/form-data" method="POST" role="form" class="php-email-form" style="width:700px" >
                
                    {{ form_start(form) }}
                    <div class="row">

                    <div class="col-6">{{ form_row(form.contrat_stage) }}</div>
                    <div class="col-6"> {{ form_row(form.carte_scolaire) }} </div>

                    </div>

                    <div class="row">

                    <div class="col-12">{{ form_row(form.entreprise,{'attr': {'class': 'form-control'}}) }}</div>

                    </div>
                    {{ form_rest(form) }}

                    <a href="{{path('app_attestation')}}">Listes des attestations</a>
                </div>
           
            </form>
     </div>
    </div>
    </div>
    </div>
</div>
{% endblock %}

templates/attestation/show.html.twig
{% extends 'template.html.twig' %}

{% block title %}Stages{% endblock %}

{% block PageTitle %}Nouvelle demande{% endblock %}

{% block body %}


<div class="container-fluid" >
<div class="card shadow mb-4">
    <div class="card-header py-3">
<div class="card-body table-responsive">
<div class="container" >
   <form action="" enctype="multipart/form-data" method="POST" role="form" class="php-email-form" style="width:700px" >
     <div class="row">
                          <div class="col-md-12 form-group mt-6 mt-md-3">
                          <label>Contration de stage:</label>
                            <img src="{{asset('uploads/users/'~ attestation.contratstage)}}" alt="" >
                          </div><br>
          
                            <div class="col-md-12 form-group mt-6 mt-md-3">
                        <label>Carte Scolaire:</label>
                          <img src="{{asset('uploads/users/'~ attestation.cartescolaire)}}" alt="" >
                        </div><br>
                         
          
                          <div class="col-md-12 form-group mt-6 mt-md-3">
                          <label>Entreprise:</label>
                            {{attestation.entreprise.nom}}
                          </div>
          
                        <div class="col-md-12 form-group mt-6 mt-md-3">
                        <label>Date de Création:</label>
                          {{attestation.createdat|date('d/m/Y')}}
                        </div>
                      



                        
                    </div>
                    </div>
                    </div>
{% endblock %}